export {
  DocumentFormat,
  isDocumentFormat,
  parseDocumentFormat,
  Rect,
  Location,
  CfiLocation,
  PageRectLocation,
  TextOffsetLocation,
  Author,
  BookAuthor,
  Book,
  BookSignature,
  Collection,
  CollectionBook,
  ReadingSessionState,
  Highlight,
  Note,
  Comment,
  Bookmark,
  BookChunk,
  AppTheme,
  MultiDocumentDisplayMode,
  InterfaceLanguage,
  DateTimeFormatPreference,
  AppPreferences,
  Preferences,
} from './models/index.js';
export type {
  CfiLocationPlain,
  PageRectLocationPlain,
  TextOffsetLocationPlain,
  AuthorProps,
  BookAuthorProps,
  BookProps,
  BookSignatureProps,
  SignatureStatus,
  CollectionProps,
  CollectionBookProps,
  ReadingSessionStateProps,
  HighlightProps,
  NoteProps,
  CommentProps,
  BookmarkProps,
  BookChunkProps,
  AppPreferencesProps,
} from './models/index.js';

export type {
  LibraryStore,
  CollectionStore,
  OverlayStore,
  DocumentImporter,
  ImportResult,
  UrlDocumentFetcher,
  UrlFetchResult,
  DocumentNormalizer,
  NormalizeResult,
  DocumentRenderer,
  OverlayPainter,
  LocationCodec,
  LocationEncodeInput,
  LocationDecodeResult,
  AiProvider,
  AiContext,
  AiAnswer,
  ExternalLibraryConnector,
  ExternalLibraryProvider,
  ExternalLibraryStatus,
  ExternalCatalogEntry,
  LinkLibraryOptions,
  SyncService,
  SyncStatus,
} from './ports/index.js';
export {
  NoOpAiProvider,
  NoOpExternalLibraryConnector,
  NoOpSyncService,
} from './ports/index.js';
