export { EpubRenderer, type EpubRendererApi } from './EpubRenderer'
export {
  CfiCodec,
  cfiCodec,
  tryEncodeCfi,
  type EpubCfiEncodeInput,
  type EpubCfiDecodeResult,
  cfiChapterSignature,
  cfiCharacterOffset,
  characterOffsetToBoundary,
  collectDescendantTextNodes,
  documentTextLength,
  elementFromCfi,
  findRangeByText,
  isTrivialSectionStartCfi,
  parseCfi,
  rangeBetweenBoundaries,
  rangeMatchesText,
  rangeTextCoverage,
  resolveCfiBoundary,
  resolveCfiRange,
  splitCfiComponents,
  type CfiBoundary,
  type CfiDomOptions,
  cfiRangesOverlap,
  splitCfiRange,
  toEpubjsDisplayCfi,
  type SplitCfiRange,
} from './cfi'
export {
  openEpubjs,
  injectEpubThemeStyles,
  applyEpubThemeVars,
  applyEpubFontSize,
  buildEpubNavState,
  toArrayBuffer,
  waitForFrames,
  EPUB_BASE_FONT_PX,
  type EpubjsHandle,
  type EpubNavState,
  type EpubPageLayout,
  type EpubTocItem,
  type EpubSelectionInfo,
  type EpubHighlightClickInfo,
  type ViewportRectLike,
} from './openEpubjs'
export {
  cfiFromLocation,
  displayedPagesFromLocation,
  type EpubDisplayedPages,
} from './progress'
