export { EpubRenderer, type EpubRendererApi } from './EpubRenderer'
export {
  CfiCodec,
  cfiCodec,
  tryEncodeCfi,
  type EpubCfiEncodeInput,
  type EpubCfiDecodeResult,
  cfiChapterSignature,
  elementFromCfi,
  findRangeByText,
  isTrivialSectionStartCfi,
  parseCfi,
  rangeBetweenBoundaries,
  rangeMatchesText,
  rangeTextCoverage,
  resolveCfiBoundary,
  resolveCfiRange,
  splitCfiComponents,
  type CfiBoundary,
  type CfiDomOptions,
  cfiRangesOverlap,
  elementToHighlightHandleRect,
  emptyHighlightHandleRect,
  iframeRangeToViewportRect,
  rangeToHighlightHandleRect,
  splitCfiRange,
  toEpubjsDisplayCfi,
  viewportRectToHighlightHandleRect,
  type SplitCfiRange,
  cfiCharacterOffset,
  characterOffsetToBoundary,
  collectDescendantTextNodes,
  documentTextLength,
} from './cfi'
export {
  openEpubjs,
  buildEpubSelectionPayloadFromDocument,
  epubFrameContextFromView,
  injectEpubThemeStyles,
  applyEpubThemeVars,
  applyEpubFontSize,
  buildEpubNavState,
  toArrayBuffer,
  waitForFrames,
  EPUB_BASE_FONT_PX,
  type EpubFrameSelectionContext,
  type EpubjsHandle,
  type EpubNavState,
  type EpubPageLayout,
  type EpubPageMode,
  type EpubSelectionPayload,
  type EpubTocItem,
} from './openEpubjs'
export {
  cfiFromLocation,
  displayedPagesFromLocation,
  type EpubDisplayedPages,
} from './progress'
