export type { BookSession } from './book-session.js'
export {
  annotationAdd,
  annotationRemove,
  annotationReplace,
  createAnnotationHistory,
  snapshotEntity,
  snapshotId,
  type AnnotationAction,
  type AnnotationHistory,
  type AnnotationSnapshot,
} from './annotation-history.js'
export {
  applyAnnotationHistoryStep,
  type AnnotationUndoHandlers,
} from './annotation-undo.js'
export type {
  Annotation,
  Annotations,
  AnnotationStatus,
  AnnotationStyle,
  AnnotationType,
} from './annotations.js'
export {
  bookmarkDtoToReaderBookmark,
  chapterIndexFromBookmarkLocationRef,
  findReaderBookmarksAtLocation,
  isReaderBookmarkAtLocation,
  packReaderBookmarkLocation,
  parseReaderBookmarkLocation,
  readerBookmarkJumpLocation,
  readerBookmarkMatchesLocation,
  resolveCurrentReaderBookmarkLocation,
} from './bookmark-persistence.js'
export {
  annotationDtoToReaderHighlight,
  epubJumpCfi,
  packReaderHighlightLocation,
  readerHighlightToAnnotationInput,
  type HighlightAnnotationInput,
} from './highlight-persistence.js'
export {
  annotationDtoToReaderTypewriter,
  epubTypewriterJumpCfi,
  parseTypewriterLocation,
  parseTypewriterPosition,
  readerTypewriterToAnnotationInput,
  serializeTypewriterLocation,
  serializeTypewriterPageRect,
  serializeTypewriterPosition,
  type TextboxAnnotationInput,
  type TypewriterLocation,
} from './typewriter-persistence.js'
export {
  TYPEWRITER_DEFAULT_COLOR_HEX,
  TYPEWRITER_DEFAULT_FONT_SIZE,
  TYPEWRITER_FONT_SIZES,
  TYPEWRITER_TEXT_COLORS,
  clampTypewriterFontSize,
  normalizeTypewriterColorHex,
  normalizeTypewriterContent,
  sanitizeTypewriterHtml,
  serializeTypewriterEditorHtml,
  typewriterContentIsEmpty,
  typewriterPlainText,
  type TypewriterBoxStyle,
} from './typewriter-rich-text.js'
export type { CollectionSummary } from './collection-summary.js'
export type {
  ImportClientResult,
  ImportErrorCode,
  ImportToastVariant,
} from './import-client.js'
export {
  NAV_FILTERS,
  filterByNav,
  filterByShelf,
  formatFileSizeMb,
  formatRelativeLastRead,
  mapBookSummary,
  matchesSearch,
  pickContinueReading,
  type BookSummaryInput,
  type LibraryBook,
  type LibraryReadingStatus,
  type NavFilterId,
  type ShelfId,
} from './library-book.js'
export {
  HIGHLIGHT_COLOR_HEX,
  TOOL_LABELS,
  highlightColorFromHex,
  nextId,
  nextReaderOverlayId,
  normalizeHighlightColorHex,
  DEFAULT_DRAW_SETTINGS,
  DRAW_COLOR_SWATCHES,
  DRAW_STROKE_WIDTHS,
  blocksSelectionContextMenu,
  isCrosshairAnnotateTool,
  isDrawingTool,
  type AnnotateTool,
  type DrawToolSettings,
  type DrawingTool,
  type InteractionTool,
  type EpubPendingSelection,
  type EpubReaderHighlight,
  type ESignStamp,
  type FakePendingSelection,
  type FakeReaderHighlight,
  type HighlightColor,
  type HighlightHandleAnchor,
  type HighlightHandleRect,
  type PageLayout,
  type PageMode,
  type PendingSelection,
  type ReaderBookmark,
  type ReaderTypewriterNote,
  type ReaderHighlight,
  type ReaderAnnotation,
  type ReaderAnnotationType,
  type ReaderAnnotationStatus,
  type ReaderNote,
  type ReaderSignature,
  type TypewriterDraft,
  type TypewriterMark,
  type TypewriterMovePayload,
  type TypewriterNoteSource,
  type TypewriterPlacePayload,
  type ViewportRect,
} from './reader-session.js'
export {
  DEFAULT_GLOBAL_READING_PREFS,
  GLOBAL_READING_PREFS_STORAGE_KEY,
  READER_THEME_COLORS,
  fontFamilyCss,
  isFontFamily,
  isFontWeight,
  isReaderTheme,
  isTextAlign,
  normalizeGlobalReadingPrefs,
  parseGlobalReadingPrefsJson,
  resolveReadingPrefs,
  toAppThemeAttr,
  type AppChromeTheme,
  type FontFamily,
  type FontWeight,
  type GlobalReadingPrefs,
  type ReaderTheme,
  type ReadingLayout,
  type ReadingMarginPreset,
  type ReadingPageMode,
  type ReadingPreferenceOverrides,
  type ResolvedReadingPrefs,
  type TextAlign,
} from './reading-prefs.js'
export {
  READING_FONT_SIZE_MAX,
  READING_FONT_SIZE_MIN,
  clampReadingFontSize,
  parseReadingLayoutMode,
  readingPrefsFromGlobal,
  readingPrefsFromSession,
  type ReadingSessionPrefsFields,
} from './reading-session-prefs.js'
export {
  findOverlappingHighlight,
  selectionHasHighlight,
} from './selection-overlap.js'
export {
  formatLastReadLine,
  shelfProgressForBook,
  type ShelfProgressView,
} from './shelf-progress.js'
