export type { BookSession } from './book-session.js'
export type { Annotations } from './annotations.js'
export type { CollectionSummary } from './collection-summary.js'
export type {
  ImportClientResult,
  ImportErrorCode,
  ImportToastVariant,
} from './import-client.js'
export {
  NAV_FILTERS,
  filterByNav,
  filterByShelf,
  formatFileSizeMb,
  formatRelativeLastRead,
  mapBookSummary,
  matchesSearch,
  pickContinueReading,
  type BookSummaryInput,
  type LibraryBook,
  type LibraryReadingStatus,
  type NavFilterId,
  type ShelfId,
} from './library-book.js'
export {
  HIGHLIGHT_COLOR_HEX,
  TOOL_LABELS,
  highlightColorFromHex,
  nextId,
  nextReaderOverlayId,
  normalizeHighlightColorHex,
  type AnnotateTool,
  type InteractionTool,
  type EpubPendingSelection,
  type EpubReaderHighlight,
  type ESignStamp,
  type FakePendingSelection,
  type FakeReaderHighlight,
  type HighlightColor,
  type HighlightHandleAnchor,
  type HighlightHandleRect,
  type PageLayout,
  type PageMode,
  type PendingSelection,
  type ReaderBookmark,
  type ReaderComment,
  type ReaderHighlight,
  type ReaderNote,
  type ReaderSignature,
  type TypewriterMark,
  type ViewportRect,
} from './reader-session.js'
export {
  DEFAULT_GLOBAL_READING_PREFS,
  GLOBAL_READING_PREFS_STORAGE_KEY,
  READER_THEME_COLORS,
  fontFamilyCss,
  isFontFamily,
  isFontWeight,
  isReaderTheme,
  isTextAlign,
  normalizeGlobalReadingPrefs,
  parseGlobalReadingPrefsJson,
  resolveReadingPrefs,
  toAppThemeAttr,
  type AppChromeTheme,
  type FontFamily,
  type FontWeight,
  type GlobalReadingPrefs,
  type ReaderTheme,
  type ReadingLayout,
  type ReadingMarginPreset,
  type ReadingPageMode,
  type ReadingPreferenceOverrides,
  type ResolvedReadingPrefs,
  type TextAlign,
} from './reading-prefs.js'
export {
  formatLastReadLine,
  shelfProgressForBook,
  type ShelfProgressView,
} from './shelf-progress.js'
