export {
  CfiCodec,
  cfiCodec,
  tryEncodeCfi,
  type EpubCfiEncodeInput,
  type EpubCfiDecodeResult,
} from './cfi-codec'
export {
  caretRangeAtPoint,
  cfiChapterSignature,
  cfiCharacterOffset,
  characterOffsetToBoundary,
  collectDescendantTextNodes,
  documentTextLength,
  elementFromCfi,
  findRangeByText,
  isTrivialSectionStartCfi,
  parseCfi,
  rangeBetweenBoundaries,
  rangeMatchesText,
  rangeTextCoverage,
  resolveCfiBoundary,
  resolveCfiRange,
  splitCfiComponents,
  installEpubjsStartContainerLogFilter,
  withEpubjsStartContainerLogMuted,
  withEpubjsStartContainerLogMutedAsync,
  type CfiBoundary,
  type CfiDomOptions,
} from './cfi-dom-range'
export {
  cfiRangesOverlap,
  splitCfiRange,
  toEpubjsDisplayCfi,
  type SplitCfiRange,
} from './selection-cfi'
